x-app-env: &app-env
  WEB_DBNAME: example
  WEB_DBUSER: example
  WEB_DBPASS: example
  WEB_DBHOST: db
  WEB_DBPORT: 3306
  DJANGO_SETTINGS_MODULE: app.settings.local
  REDIS_CACHE_URL: redis://redis:6379/1
  REDIS_SESSION_URL: redis://redis:6379/2
  CELERY_BROKER_URL: redis://redis:6379/3
  CELERY_RESULT_BACKEND: redis://redis:6379/4

services:
  db:
    image: mysql:8.0
    container_name: server_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example

  redis:
    image: redis:7-alpine
    container_name: server_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - redis_data:/data

  web:
    build: .
    container_name: server_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      <<: *app-env

  celery_worker:
    build: .
    container_name: server_worker
    command: celery -A app worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      <<: *app-env

  celery_beat:
    build: .
    container_name: server_beat
    command: celery -A app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      <<: *app-env

volumes:
  db_data:
  redis_data: